### ISSUE TITLE
One disk resulting Segmentation fault

### ISSUE THREAD

**Issue by livibetter** [scootersmk/rkrellm#1]
Using b7caf31e004ae48fbd0dd01875cc74aa3719e381

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6f10d1b in vfprintf () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff6f10d1b in vfprintf () from /lib64/libc.so.6
#1  0x00007ffff6f32f3b in vsprintf () from /lib64/libc.so.6
#2  0x00007ffff6f17227 in sprintf () from /lib64/libc.so.6
#3  0x0000000000406f66 in graph_disk (win=0x65b400) at rkrellmDisk.c:107
#4  0x0000000000401fc2 in setup_screen (windows=0x7fffffffd710) at rkrellmDisplay.c:143
#5  0x000000000040853e in main (argc=1, argv=0x7fffffffd848) at rkrellm.c:152
(gdb) b rkrellmDisk.c:107
(gdb) r
[...]
Breakpoint 1, graph_disk (win=0x65b400) at rkrellmDisk.c:107
107       sprintf(disk_head_str, "%s:%4lld%c/%4lld%c",
(gdb) p disk_count
$1 = 1
(gdb) p disks
$2 = (sg_disk_io_stats *) 0x660400
(gdb) p disks->disk_name
$3 = 0x30 <Address 0x30 out of bounds>
```

I commented out L97:

```
  // disks++;
```

rkrellm seems to run fine, just the two graphs are showing the same, which is to be expected. It looks like to me the disk part is fixed to 2 disk drives.

By the way, the README needs to note that the dependency libstatgrab must be <= 0.17, the current code won't compile with libstatgrab 0.90+.

**Comment by scootersmk** [comment]
Thanks for debugging that and for the feedback. Info has been added to README. Hopefully will get some more flexible disk code written soon.

**Comment by livibetter** [comment]
I'm closing this to keep my Issues list clean, please create a new one if necessary.
